name: Build and Publish to PyPI

on:
  push:
    branches: [master, main, dev]  # TBD - Replace with other spec
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:

  build-and-publish:

    name: Build and Publish
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'Run Tests'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python (3.12)
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Flit
      run: |
        python -m pip install --upgrade pip
        python -m pip install flit
        flit --version

    - name: Build the package
      run: flit build --no-use-vcs

#    - name: Publish to PyPI
#      run: flit publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
